credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: fscottmiller
              username: fscottmiller
              password: ${GIT_PASSWORD}