jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
            assignments:
              - "authenticated"
        items:
          - name: "Homestead"
            description: "let homestead users see only their project"
            pattern: "Homestead.*"
            permissions:
              - "Job/Configure"
              - "Job/Build"
              - "Job/Delete"
              - "Job/Read"
              - "View/Read"
            assignments:
              - "homestead"
          - name: "dashboard"
            description: "let dashboard users see only their project"
            pattern: "Dashboard.*"
            permissions:
              - "Job/Configure"
              - "Job/Build"
              - "Job/Read"
              - "View/Read"
            assignments:
              - "dashboard"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "password"
        - id: "dashboard"
          password: "dashboard"
        - id: "homestead"
          password: "homestead"