jobs:
  - script: >
        multibranchPipelineJob('Deploy X') {
            branchSources {
                branchSource {
                    source {
                        git {
                        id('jenkins-config')
                        remote('https://dev.azure.com/markelcorp/DevOps%20and%20QE/_git/Jenkins')
                        credentialsId('repo-creds')
                        }
                    }
                    strategy {
                        defaultBranchPropertyStrategy {
                            props {
                                noTriggerBranchProperty()
                            }
                        }
                    }
                }   
            }
            properties {
                pipelineTriggerProperty {
                    deleteActionJobsToTrigger("Cleanup")
                    branchIncludeFilter("*")
                }
            }
            orphanedItemStrategy {
                discardOldItems {
                    numToKeep(10)
                }
            }
        }
  - script: >
      pipelineJob('Cleanup') {
          definition {
              cpsScm {
                  scm {
                      git {
                          branch('continuousIntegration')
                          remote {
                              url('https://dev.azure.com/markelcorp/DevOps%20and%20QE/_git/Jenkins')
                              credentials('repo-creds')
                          }
                      }
                  }
                  scriptPath('cleanup.jenkins')
              }
          }
      }
      