jobs:
  - script: >
        pipelineJob('Deploy') {
            definition {
                cpsScm {
                    scm {
                        git {
                            branch('tmp')
                            remote {
                                url('https://github.com/fscottmiller/Jenkins')
                            }
                        }
                    }
                }
            }
        }
#   - script: >
#       pipelineJob('Cleanup') {
#           definition {
#               cpsScm {
#                   scm {
#                       git {
#                           branch('continuousIntegration')
#                           remote {
#                               url('https://dev.azure.com/markelcorp/DevOps%20and%20QE/_git/Jenkins')
#                               credentials('repo-creds')
#                           }
#                       }
#                   }
#                   scriptPath('cleanup.jenkins')
#               }
#           }
#       }
      