jobs:
  - script: >
        pipelineJob('Deploy') {
            definition {
                cpsScm {
                    scm {
                        git {
                            branch('tmp')
                            remote {
                                url('https://github.com/fscottmiller/Jenkins')
                            }
                        }
                    }
                }
            }
        }
  - script: >
        pipelineJob('SonarQube') {
            definition {
                cpsScm {
                    scm {
                        git {
                            branch('tmp')
                            remote {
                                url('https://github.com/fscottmiller/Jenkins')
                            }
                        }
                    }
                    scriptPath('sonar.jenkins')
                }
            }
        }
